### ISSUE TITLE
Expose a REST-hooks API to the client

### ISSUE THREAD

**Issue by AlexTheDragon8** [WciJam/cloudtrax#1]
# Expose a REST-hooks API to the client

> The server will accept POST requests for REST-hook callback points.

The client will send a request to the server: `POST /callbacks?url=[url]`. This will be added to the server's internal callbacks list. When a message is available, the server will send a POST to the indicated URL with the message as the body.

##### Subtasks

- [ ] Maintain a list of callbacks
- [ ] Accept callback registration
- [ ] Send messages to callbacks

##### Works Towards

N/A
