### ISSUE TITLE
Listen for State Changes with the CloudTrax API

### ISSUE THREAD

**Issue by AlexTheDragon8** [WciJam/cloudtrax#2]
# Listen for State Changes with the CloudTrax API

> The server should be able to detect changes in the list of users connected to the CloudTrax mesh network, and interpret these changes as Movement Events.

A Movement Event will be a structure of a MAC address, an initial location, and a new location. These Movement Events will be appended to an internal queue.

##### Subtasks

- [ ] Connect to the CloudTrax API
- [ ] Listen on state changes
- [ ] Decode movement events

##### Works Towards

N/A
