### ISSUE TITLE
Apply Rules to Movement Events

### ISSUE THREAD

**Issue by AlexTheDragon8** [WciJam/cloudtrax#3]
# Apply Rules to Movement Events

> The server will check movement events against a set of rules, and convert them to messages.

A rule may have criteria regarding the MAC address, the initial location, and the new location of the device in question. When a message is received, the server will determine if the rule matches, and if it does, what message needs to be sent.

##### Subtasks

- [x] Maintain a list of rules
- [x] Be able to check an event against a rule
- [x] Check all incoming Movement Events
- [x] Be able to dispatch messages

##### Works Towards

N/A

**Comment by AlexTheDragon8** [comment]
This has been tested quite extensively by me and @null-dev , and no problem has been found.
